name: Deploy to Developer Portal Bucket

on:
  push:
    branches:
      - main
      - chore/deploy-to-gcs
    paths:
      - '.github/workflows/deploy-to-developer-portal.yml'
      - 'docusaurus/**'
jobs:
  deploy:
    name: Deploy docs to Developer Portal Bucket
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
      
        #mac: sed -i '' 's/title: Data Plane Contract - Technical Specification/title: Data Plane Contract - Technical Specification\nslug:\ \//g' ./docs/contract/contract.md
        #linux: sed -i 's/title: Data Plane Contract - Technical Specification/title: Data Plane Contract - Technical Specification\nslug:\ \//g' ./docs/contract/contract.md
      - name: Make docs the homepage of this subsite
        run: |
          rm -f ./docusaurus/website/src/pages/index.tsx
          sed -i 's/title: Data Plane Contract - Technical Specification/title: Data Plane Contract - Technical Specification\nslug:\ \//g' ./docs/contract/contract.md
          
      - name: Build documentation website
        run: npm run docs:build -- --config docusaurus.config.devportal.js
        
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Deploy to Developer Portal Bucket
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: './docusaurus/website/build/'
          destination: 'grafana_developer_portal/plugin-tools'
          parent: false